Contact form section
ChrispaixK/Microverse_Portfolio pull request #3
Opened 2022-05-31 16:33 UTC by ChrispaixK

# Microverse_Portfolio : Contact Section

In this PR I and my partner :
* Add Contact section in html
* Add style for contact section in CSS
* Add an image for the Contact section background

2022-05-31 16:49 UTC, Kossi-stack requested changes
## Hi @,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly edit the PR's title to something more descriptive. it can be "Hello Microverse Project PR or Hello Microverse Project".
 - [ ] Please make sure to use [this readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) and please be sure to edit all of the sections to better suit your project.
- [ ] Kindly make sure to use [these linters](https://github.com/microverseinc/linters-config/tree/master/html-css) provided by Microverse and make sure they are set up correctly and they all pass with green checkmarks.
 - [ ] Kindly add descriptive pull request message, This helps other programmers who want to take a look at your code understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-31 16:49 UTC, Kossi-stack commented on index.html
> +                    <input type="text" class="input" name="name" placeholder="Enter your name" />
- [x] Kindly make sure the name input has _maxlength="30"_

2022-05-31 16:49 UTC, Kossi-stack commented on index.html
> +                    <textarea class="text-area" name="message" placeholder="Write your message here"
- [ ] Kindly make sure the message input has _maxlength="500"_

2022-06-01 08:32 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @ChrispaixK,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 08:35 UTC, ChrispaixK commented
Thank you @TedLivist  and @Kossi-stack 👍🏾

2022-06-01 08:36 UTC, merged